### ISSUE TITLE
Redesign Post Detail Template

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#104]
Modify post-detail template
Add the following in order:
- [x] Heading
- [x] Synopsis
- [x] Cover image
- [x] Content
- [x] Social media sharing options
- [x] Comments Section

**Comment by ighosh98** [comment]
Template ideas:
1. https://editor.wix.com/html/editor/web/renderer/new?siteId=f3b2f82b-4eef-4d1a-bcbb-9b4113eab7d0&metaSiteId=973ef088-80a8-49a4-8cc8-19bbb3647254&editorSessionId=23ee4558-0937-4650-adb4-64bde8e17890
2. https://www.wix.com/website-template/view/html/2233?siteId=1f41a9aa-d93b-4b62-bb99-184426438764&metaSiteId=bf6bd92f-0059-4fd6-8781-7edc83d7ad97&originUrl=https%3A%2F%2Fwww.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Fblogs-and-forums
3. https://www.wix.com/website-template/view/html/1312?siteId=c4e97b6d-b9c1-40ed-af57-3e7dddbde3d8&metaSiteId=af6dcf6f-e49f-417d-8212-ec8fa5cc4c0b&originUrl=https%3A%2F%2Fwww.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Fblogs-and-forums
4. https://www.wix.com/website-template/view/html/1343?siteId=91423ff4-1d32-4f2e-8897-4d72d1f2b8e3&metaSiteId=33bfd795-cb47-4bc4-ac2e-f4413e8bb143&originUrl=https%3A%2F%2Fwww.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Fblogs-and-forums

**Comment by ighosh98** [comment]
@HimanshuAgarwal022 start working on this issue when you are finished with remaining issues

**Comment by ighosh98** [comment]
Solved by #103. Closing issue.

**Comment by ighosh98** [comment]
Social media sharing options have not been added yet.

**Comment by HimanshuAgarwal022** [comment]
we should use disqus for comments and social links...

**Comment by ighosh98** [comment]
@HimanshuAgarwal022 add the commit to your PR.

**Comment by HimanshuAgarwal022** [comment]
done check frontend2

**Comment by ighosh98** [comment]
All tasks completed in #148. However, bugs need to fixed . [As addressed in #159 ]
