### ISSUE TITLE
Monitor Site Traffic

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#105]
- [x] When the site is hosted, the site traffic should be monitored on a monthly and yearly basis.
- [x] Also provide an article wise traffic analysis
Fields necessary:
- [x] Number of unique IPs
- [x] Number of Visits

**Comment by Ak-shay** [comment]
We can use [Google Analytics](https://analytics.google.com/analytics/web/provision/?authuser=0#/provision)
Have a look

**Comment by ighosh98** [comment]
To be implemented. I will handle this issue. Last issue to be addressed in #114.

**Comment by ighosh98** [comment]
Not yet fixed. I will finish this one later. Add it once the site is hosted.
