### ISSUE TITLE
Modify post_list UI

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#106]
- [x] Add symbols for the author, date of publication, Section and Editor.
- [x] Fix the MastHead(Add the name of the section the user is viewing at that moment to the masthead)
- [x] Display the cover image for every post along with the synopsis.
- [x] Implement infinite scroll

**Comment by Ak-shay** [comment]
for symbols use from post-detail view

**Comment by ighosh98** [comment]
Refer to #112 for task 2.

**Comment by ighosh98** [comment]
Add the cover image please @HimanshuAgarwal022 and implement infinite scroll. @UnlaxedNeurotic can implement the rest.

**Comment by ighosh98** [comment]
Solved. Fix the minor issues left @HimanshuAgarwal022 on the branch restructure. Fixed in #117 and #114.
