### ISSUE TITLE
Issues Left in the Backend

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#115]
Check out these Issues @Ak-shay :
- [x] Handle integrity errors. They are raised when an article of the same title is added. 
- [x] I am unable to add images on my articles inside the post. (Test using the backend of the old website. Use [this article](http://www.freelunch.co.in/wp-admin/post.php?post=2167&action=edit) as sample)
- [x] Cover image is not being displayed even after it is uploaded.
- [x] This page is getting displayed
![Screenshot from 2019-06-26 23-03-28](https://user-images.githubusercontent.com/27827510/60202403-1fdb5780-9868-11e9-9830-d4ecf75a1263.png)
when you click on Visit on Site.
![Screenshot from 2019-06-26 23-04-33](https://user-images.githubusercontent.com/27827510/60202417-2538a200-9868-11e9-8304-e68c0fec7ef9.png)

The preferred format has been discussed with you @Ak-shay 

- [x] Modify the writers model to add the editor's profiles(Editor-in-Chief etc.) as well. We will modify the contributor's page accordingly.

**Comment by ighosh98** [comment]
Fix in the #114 on the branch restructure.

**Comment by Ak-shay** [comment]
Title of a article is its unique, it cant be same..
Also title is being used to make slug which is unique.
Moreover, there will be no article with same title

**Comment by ighosh98** [comment]
Closing issue as it is solved in #114.
