### ISSUE TITLE
Add a default Cover Image and  synopsis

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#116]
- [ ] If cover image not added. The website should not result in 404 or similar errors. @HimanshuAgarwal022 will elaborate on this by posting an image.
- [x] If the synopsis is not added and the field is empty, then by default the first paragraph of the article would become the synopsis.

**Comment by Ak-shay** [comment]
Do we really need default?
Cover image should be in accordance to the article.
High chances of  posting  it with default.

**Comment by Ak-shay** [comment]
If we doesn't provide synopsis then we must add starting few characters(like 640) of main content instead of first para..As it may have more than required characters which may not look good.

**Comment by ighosh98** [comment]
Details regarding Synopsis is discussed. If the sentence exceeds the prescribed character limit, cut the last sentence out

**Comment by Ak-shay** [comment]
first para of content will be the synopsis, if synopsis is blank

**Comment by ighosh98** [comment]
Solved by #114.
