### ISSUE TITLE
Cover images are improperly displayed in masthead

### ISSUE THREAD

**Issue by unlaxedneurotic** [BITS-Periodical-Society/freelunch#118]
Cover images in masthead in post-detail template are not displayed properly . Check posts 'What Narcos Doesn't Tell You' or 'Automated image labelling...' to see the issue.

**Comment by Ak-shay** [comment]
Its not an issue..
We need to add cover  image to respective article and it will be sorted..
This issue will not raise again as cover_image field is neccessary..
