### ISSUE TITLE
If title of article is of more than one line, post-detail view doesnt show section, editor, time...etc

### ISSUE THREAD

**Issue by Ak-shay** [BITS-Periodical-Society/freelunch#120]
In laptop screen lines below title is not visible..

**Comment by ighosh98** [comment]
Please look into a fix for this @HimanshuAgarwal022. @Ak-shay please add more images to describe the bug.
**Note**: Try to follow the [ Bug report template](https://github.com/BITS-Periodical-Society/freelunch/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) next time.
**Edit**: I will look into this issue.

**Comment by Ak-shay** [comment]
![fl](https://user-images.githubusercontent.com/46865292/60430093-13654f00-9c1a-11e9-9294-977fcfc0c115.png)
![fl2](https://user-images.githubusercontent.com/46865292/60430096-13fde580-9c1a-11e9-8d37-1bd9b23dc8d9.png)
These two are bugs.
For first pic date goes down
For second pic that row doesn't show due 2 line title

**Comment by ighosh98** [comment]
Fixed this bug. Please verify by referring to the last commit on #114.  @Ak-shay
