### ISSUE TITLE
Force the editor or post creator to necessarily add a cover image

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#125]
Has this been solved? @Ak-shay

**Comment by Ak-shay** [comment]
Yes ..
Without adding cover image post will not create

**Comment by Ak-shay** [comment]
We can have message below cover input if u want

**Comment by ighosh98** [comment]
Keep a default cover image, just to be safe. It would help save some time during testing as well

**Comment by ighosh98** [comment]
Also work on ensuring that the image fits into the decided dimension. It should not get cropped

**Comment by ighosh98** [comment]
Solved in #114.
