### ISSUE TITLE
Animation based bugs

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#126]
Animations created by #31 have bugs. 
One of the bugs spotted:
![Screenshot from 2019-07-01 17-54-21](https://user-images.githubusercontent.com/27827510/60436258-4ebb4a00-9c29-11e9-9222-f3be50b8c0fe.png)
The color changes weirdly in the middle of the article. Upon inspection, it is found to be a JS based bug. Look at the customized JS added here. There are bugs in it.

**Comment by ighosh98** [comment]
Add any more animations if required.

**Comment by Ak-shay** [comment]
Is it a post specific bug..
I am unable to regenerate it.

**Comment by ighosh98** [comment]
Fixed. Nevermind
