### ISSUE TITLE
Image size restrictions

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#128]
- [x] Work on ensuring that the image(cover images as well as images in a post) fits into the decided dimension. It should not get cropped.

**Comment by unlaxedneurotic** [comment]
Should the image be resized in case it's aspect ratio does not match the one specified?
@ighosh98

**Comment by HimanshuAgarwal022** [comment]
I have made the image container responsive in post detail
it won't get cropped now
ref. frontend2 branch.
