### ISSUE TITLE
Uncaught Reference error: Waypoint is not defined 

### ISSUE THREAD

**Issue by Ak-shay** [BITS-Periodical-Society/freelunch#139]
## Regenerate
Go to `127.0.0.1` .
Open developers console.
In console you will see this error.
![Screenshot from 2019-07-02 02-44-16](https://user-images.githubusercontent.com/46865292/60467295-e34a9a00-9c73-11e9-9c76-2cc0726fe0d8.png)

## Origin of error
This error is related to script in `post_list.html` at `line: 8`.

**Comment by ighosh98** [comment]
That is some animation @HimanshuAgarwal022 is working on and left the code there. @HimanshuAgarwal022 clean it up if it is not required.

**Comment by ighosh98** [comment]
Should be solved by #140. CDN added instead of static files.

**Comment by Ak-shay** [comment]
Its still there...
I have written origin of error.
