### ISSUE TITLE
Mobile View Compatibility Testing

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#141]
Test if all the features appear appropriately in Mobile View and submit issues in comments below. 

- [x] Alignment issues of symbols in post details
- [x] Post detail margin needs to be correected

**Comment by ighosh98** [comment]
Solved by #140.

**Comment by HimanshuAgarwal022** [comment]
post detail margin corrected and some background shadows added to post list and detail in branch frontend2.

**Comment by ighosh98** [comment]
No more bugs reported in mobile compatibility testing. Closing issue.
