### ISSUE TITLE
Add Guest Authors and Founders

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#150]
- [x] Modify the authors.html template to add a section of Founders and Guest Authors.
Format:
- [x] Founders: Same as developers and writers.
- [x] Guest Authors: Simply list their names with hyperlinks to their profile page. No images or anything.

**Comment by Ak-shay** [comment]
In the new commit to master..
Founder model is added..

In contributors page..
There are four section:
FOUNDER
EDITOR
SECTION
WRITER

**Comment by ighosh98** [comment]
Related to #168.
