### ISSUE TITLE
Modify Footer

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#151]
- [x] Add the name of the development team members to the bottom:
@abhishekspeer,@ighosh98, @Ak-shay, @HimanshuAgarwal022 , @UnlaxedNeurotic 
**[Refer to the README and discuss with me directly if you have doubts regarding the members]**
- [x] Add Hyperlink to their profile pages if they exist.

**Comment by HimanshuAgarwal022** [comment]
no frontend needed just link the backend

**Comment by ighosh98** [comment]
Names haven't been added to the footer. No updates from @HimanshuAgarwal022. Reassigning. Hard code it please @Ak-shay

**Comment by ighosh98** [comment]
Fixed
