### ISSUE TITLE
Show all articles of an author on his profile page

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#152]
- [x] Modify `authors.html` to show all the articles written by an author on his profile page.
- [ ] Implement infinite scroll on the profile page(Authors.html)

**Comment by Ak-shay** [comment]
In the new commit to master..
`Founder` model is added..

In `contributors` page..
There are four section:
FOUNDER
EDITOR
SECTION
WRITER

**Comment by unlaxedneurotic** [comment]
Handled in PR #164. I don't think we need to implement infinite scroll to the profile page. All the post titles are displayed as a list which hyperlink to the respective posts and will show all the items.
@ighosh98
