### ISSUE TITLE
More information regarding `populate_site.py` script

### ISSUE THREAD

**Issue by unlaxedneurotic** [BITS-Periodical-Society/freelunch#157]
The `populate_site.py` script is written to automate the creation of fake data (see issue #66 ).
The script adds `author`, `editor`, `post` and `comment` objects to the sqlite3 database.
The date-time-fields added are naive as they in no way affect our purpose and any warning messages regarding this can be ignored.

_Screenshots:_

Install the library
![Installation](https://user-images.githubusercontent.com/47986362/60656272-ccbb6300-9e6c-11e9-80cf-4427ac0c4917.png)

Run the script
![Running the script](https://user-images.githubusercontent.com/47986362/60656303-d8a72500-9e6c-11e9-91f6-1d346192915e.png)

Specify the numbers
![Runtime1](https://user-images.githubusercontent.com/47986362/60656313-dba21580-9e6c-11e9-82d1-2c32a5b59c71.png)

Wait for the process to complete. The 'naive datetime' warning can be ignored
![Runtime2](https://user-images.githubusercontent.com/47986362/60656322-dd6bd900-9e6c-11e9-9eb0-d9c7502203f6.png)

All done!
![Done](https://user-images.githubusercontent.com/47986362/60656337-dfce3300-9e6c-11e9-9061-34fa436c0192.png)

**Comment by ighosh98** [comment]
Thanks for the tutorial! Closing this issue
