### ISSUE TITLE
Subscribe form window is not closing automatically

### ISSUE THREAD

**Issue by Ak-shay** [BITS-Periodical-Society/freelunch#161]
## Regenerate
Click on `subscribe`from the nav bar.
It opens a new window for form.

## Issue
This new window redirect us to our site page after user has subscribed to our site.

## Expectation
This window should be closed on clicking `submit`, on verifying user detail (EMAIL).

**Comment by unlaxedneurotic** [comment]
Fixed in commit [`06f72a2`](https://github.com/BITS-Periodical-Society/freelunch/commit/06f72a2fc1d20a1e68d5b6a57ecfdab324d88d85) to `master`.
