### ISSUE TITLE
populate_site.py needs to upgraded

### ISSUE THREAD

**Issue by Ak-shay** [BITS-Periodical-Society/freelunch#162]
## Improvement
All variables should be in consider with our `models.py`.
Current variable names doesn't make sense.
The `designation` variable has been changed..
Make `user` prompt with more detail exceptions and allow them to re-input that field.

## New
`Founder` model is added, add fake script for this too.

**Comment by unlaxedneurotic** [comment]
Fixed in commit [f2d1eca](https://github.com/BITS-Periodical-Society/freelunch/commit/f2d1eca80c62322822d3055b1041a2cea40a84a1)
