### ISSUE TITLE
Identify recently published articles

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#166]
- [ ] We intend to identify articles published in the last 14 days and mark them as featured articles which would be put up on the masthead of the website.
- [ ] The scrolling masthead looks horrendous. Fix it. Everything about it is wrong.

**Comment by Ak-shay** [comment]
it can be easily done using filter in views..
if we need top 4 then use loop indexing

**Comment by ighosh98** [comment]
We will use loop indexing then.

**Comment by Ak-shay** [comment]
@ighosh98

**Comment by ighosh98** [comment]
Don't think we need this at the moment. Closing it for now
