### ISSUE TITLE
Change Heading Text colour 

### ISSUE THREAD

**Issue by abhishekspeer** [BITS-Periodical-Society/freelunch#175]
White looks good, but it's not clearly visible. I'd be great if we could come up with an alternative for the same.
I'd suggest a gradient effect on green text. Also, I'm open to suggestions on this one.
![Screenshot from 2019-07-06 20-46-50](https://user-images.githubusercontent.com/33948877/60759338-473cdc00-a041-11e9-8253-6dcd81f92aa0.png)

**Comment by unlaxedneurotic** [comment]
@ighosh98 @HimanshuAgarwal022 @Ak-shay @abhishekspeer
Will any of these work? 
![img1](https://user-images.githubusercontent.com/47986362/60760966-9e9c7580-a05c-11e9-90a3-983294bed6cb.jpg)
#003333 - #339966
![img3](https://user-images.githubusercontent.com/47986362/60761056-b8d75300-a05e-11e9-817a-91d6555185c2.jpg)
![img4](https://user-images.githubusercontent.com/47986362/60761058-bbd24380-a05e-11e9-89d6-1c027a2699e1.jpg)
![img2](https://user-images.githubusercontent.com/47986362/60761007-97299c00-a05d-11e9-9d99-e63a56f2ea30.jpg)

**Comment by abhishekspeer** [comment]
We do not need any background fill. Just gradient in text colour. The background looks good for now.
