### ISSUE TITLE
Change logo of title of site pages

### ISSUE THREAD

**Issue by Ak-shay** [BITS-Periodical-Society/freelunch#182]
We have new logo in our recent commits.
This should be replaced with our current on left of tab.
See the tabs
![Screenshot from 2019-07-07 20-32-20](https://user-images.githubusercontent.com/46865292/60770225-5af64a00-a0f6-11e9-9a88-b7e198c57e66.png)

**Comment by ighosh98** [comment]
Logo remained the same. Closing this.
