### ISSUE TITLE
Front end Templates

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#2]
As discussed, build the templates for the Frontend web pages.

- [x]  Implement Home Page
- [x]  Implement a common template for all sections of the website[Eg: Science Tech, EcoFin, etc.]
- [x] Create a page for contributors as discussed. Combined with About Us and other such information.
- [x] Code Cleanup.
- [ ] Structure the code base properly.
- [x] Implement infinite scrolls wherever necessary

Deadline: 28 May

**Comment by HimanshuAgarwal022** [comment]
I will probably start work tomorrow.
Is there any general idea of how the design should look?
Also, the colour theme.

**Comment by ighosh98** [comment]
@HimanshuAgarwal022  Follow the General design ideas as discussed. You have the freedom to tweak color palette. Try using gradient effects. The issue has been updated to reflect the templates that need to be created and related details. Send a combined PR or PR for the separate tasks.

**Comment by HimanshuAgarwal022** [comment]
all done see the PR.

**Comment by ighosh98** [comment]
Check the latest commit @abhishekspeer 
All cache files have been removed and renaming has been handled. Point out any other errors.

**Comment by HimanshuAgarwal022** [comment]
@ighosh98 @abhishekspeer is there anything else needed for the frontend?
also, are the templates working correctly on your systems?

**Comment by ighosh98** [comment]
Also if there are no other errors @HimanshuAgarwal022  please to restructure the project and the code as suggested by the first answer on [this link](https://stackoverflow.com/questions/22841764/best-practice-for-django-project-working-directory-structure). Kindly wait till all merge conflicts have been solved and all other errors have been removed from the code.

**Comment by ighosh98** [comment]
@JessePinkman7 implement the infinite scroll feature and search and fix all the bugs that you can find. Report the bugs to the issue tracker before starting work.

**Comment by abhishekspeer** [comment]
Is anyboady still working on this one?

**Comment by abhishekspeer** [comment]
Is anybody still working on this one?

**Comment by ighosh98** [comment]
@abhishekspeer Infinite scroll is left. The rest is done. @JessePinkman7  is out for some time. Issue can be reassigned if it is urgently required

**Comment by ighosh98** [comment]
@Ak-shay  Please to restructure the project and the code as suggested by the first answer on [this link](https://stackoverflow.com/questions/22841764/best-practice-for-django-project-working-directory-structure).

**Comment by ighosh98** [comment]
@HimanshuAgarwal022  @JessePinkman7 Start working on making the template specific to the website from tomorrow. Restructure the paths according to the new project structure. Work together on getting it more specific. You can pick one article from each of the sections as an example from http://www.freelunch.co.in/
Deadline 28 June

**Comment by ighosh98** [comment]
Infinite scroll not yet implemented. I don't see anyone working on restructuring the code either.

**Comment by ighosh98** [comment]
Code cleanup carried out.
Work on the templates-backend branch for the time being. Need codebase restructuring and implementation for infinite scrolling.
Final deadline for implementation: 30 June
@JessePinkman7 @HimanshuAgarwal022 
Else, I'll reassign.
