### ISSUE TITLE
hovering social links of contributors

### ISSUE THREAD

**Issue by Ak-shay** [BITS-Periodical-Society/freelunch#202]
# Footer
Logo of facebook turn green on hovering whereas other logo (github and linkedin) turns grey.

**Comment by Ak-shay** [comment]
Same issue in profile page view.

**Comment by unlaxedneurotic** [comment]
I could not reproduce the issue. Is it only happening in a certain branch or browser? @Ak-shay 

![Screenshot (85)](https://user-images.githubusercontent.com/47986362/61992020-38f94300-b076-11e9-9fcf-2fb8697e6583.png)
![Screenshot (84)](https://user-images.githubusercontent.com/47986362/61992023-3e568d80-b076-11e9-9823-c105bfefec7a.png)

**Comment by Ak-shay** [comment]
It is on profile of user.
Hover  on user links

**Comment by ighosh98** [comment]
Is this fixed? @Ak-shay @UnlaxedNeurotic

**Comment by unlaxedneurotic** [comment]
I still can't reproduce the issue, except on the hosted website. The master branch does not has this issue. @ighosh98
