### ISSUE TITLE
Script for adding contributors

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#21]
Write a script that every contributor must run before they start contributing. The script should do the following:
- [ ] Star all the repositories of the organization.
- [ ] Make the user watch all the repositories of the organization.
- [ ] Add instructions on how to run the script.
- [ ] Kindly add proper documentation to the code. If required, we can create a separate repository for this issue.

**Comment by abhishekspeer** [comment]
@ighosh98 @JessePinkman7 
I will not recommend implementing this. Users, at least the more experienced bunch, DO NOT prefer doing this as they have a lot of projects and they only want to star and watch the repositories they actually need to. 
Please let me know if you have a different perspective about the same. Closing this for now. If necessary, we'll open it again. 
Thanks for your effort!

**Comment by ighosh98** [comment]
@abhishekspeer Fossasia has this feature. We want to implement this only for people who send a PR or make a significant contribution, beyond reporting bugs. Also, it would be a good coding exercise. Could be optionally implemented in the long run for practice.

**Comment by ighosh98** [comment]
Closing for now. Can be done as a personal project later
