### ISSUE TITLE
Resolve conflicts between master and development branch

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#27]
Please add detailed references for handling future conflicts.
Suggested reference https://help.github.com/en/articles/resolving-a-merge-conflict-using-the-command-line

**Comment by abhishekspeer** [comment]
I had a look at this one. We'll have to compare a lot of files (1500+) to resolve merge conflicts.
Instead, we should make a new branch, sync it with master and add the changes to add what we have done in `development` branch. Once this is done, we can make a PR from this branch and can merge it to `master`.

**Comment by ighosh98** [comment]
@abhishekspeer There are only seven files with merge conflicts. Check PR #32 .
