### ISSUE TITLE
Form for adding articles

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#3]
Following features must be implemented:
- [x] Date of Publication
- [x] Name of Author
- [x] Section
- [x] Name of editor
- [x] Main article: You should be able to add text, latex formulas and images at any point in the main article.
- [x] Synopsis(Set an upper limit of 80-90 words[on an avg 8 letter words])[Compulsory field]
- [x] Heading(150 Characters)[Compulsory field]
- [x] Fix the font size, style, and other related parameters.[Compulsory field]

**Comment by ighosh98** [comment]
@Ak-shay refer to http://freelunch.co.in for ideas. Let me know if there are any other queries by adding a comment here. Once you are done, add your name to the list of contributors on the README.md and send a PR.

**Comment by Ak-shay** [comment]
I think we need another model for Article content which have photos and sections fields because for the CharField (current field for content) it will be difficult to handle and add all this.

**Comment by ighosh98** [comment]
All right. Go ahead @Ak-shay . Unless there is a neater solution. Is there a neater solution @abhishekspeer ?

**Comment by ighosh98** [comment]
Solved partially.

**Comment by ighosh98** [comment]
Customizing font style is the only part of the issue which is left to be solved.
