### ISSUE TITLE
Add Animations

### ISSUE THREAD

**Issue by abhishekspeer** [BITS-Periodical-Society/freelunch#31]
Though we are at very early stage, I think this is the time we should be looking for some animations to support our overall design. 
Explore different projects, search on google for animations we can use and discuss it with mentors before you start working on it. 
Once done, implement and submit a patch for our reviews!

**Comment by ighosh98** [comment]
Tutorials:
https://www.youtube.com/watch?v=ePgnR4gHIi4
https://learn.shayhowe.com/advanced-html-css/css-transforms/
https://wicg.github.io/scroll-animations/
https://scotch.io/tutorials/implementing-a-scroll-based-animation-with-javascript
https://www.sitepoint.com/scroll-based-animations-jquery-css3/
https://codepen.io/tag/css-animation/3/
https://codepen.io/cedrickcapacete/pen/ezZBVp?page=8
Stack needed: JS, hQuery, CSS

**Comment by Ak-shay** [comment]
We need opinions for diff animations....

**Comment by ighosh98** [comment]
Solved partially by #117.
