### ISSUE TITLE
Form for adding Contributors

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#4]
The following Features need to be implemented:
- [x] Contributors must be classified as Guest Authors and Core team members for the writing team.
 - [x] Highlight Section editors and chief editors for the writing team. 
 - [x] Highlight Founders 
 - [ ] Highlight Guest Authors
- [ ] A form must also allow admin to add members of the backend team.  
- [x] All members must have a section on bio.

**Comment by ighosh98** [comment]
Deadline: 21st June. @UnlaxedNeurotic updates on this issue?
I'll reassign if you are busy.

**Comment by ighosh98** [comment]
Has this been handled yet? @UnlaxedNeurotic @Ak-shay

**Comment by Ak-shay** [comment]
I am handling all this in #45

**Comment by Ak-shay** [comment]
But not sure about the forms..
Please elaborate

**Comment by ighosh98** [comment]
Let @UnlaxedNeurotic work on it till tomorrow. So the form is a simple one.
1. A field for position(Section editor, Core team member etc. )
2. Field for name
3.  Social media IDs(LinkedIN, Github(May hold NULL values)) 
4.  A field for position of the member(Writing Core team/Guest Author/Developer)
 Start work on Saturday if this is not solve by then @Ak-shay .
I hope this makes sense.

**Comment by ighosh98** [comment]
Necessary models have been created in #68

**Comment by ighosh98** [comment]
Finish the remaining task of creating the form.

**Comment by ighosh98** [comment]
This is not yet completed.

**Comment by Ak-shay** [comment]
@ighosh98 
Do we need forms?
We can add anything in admin panal.

**Comment by ighosh98** [comment]
All forms are for the chief editor to add stuff

**Comment by ighosh98** [comment]
solved
