### ISSUE TITLE
Correction in Installation guide included in README.md

### ISSUE THREAD

**Issue by abhishekspeer** [BITS-Periodical-Society/freelunch#41]
Change `virtualenv virtualenv` to `virtualenv venv`
Also, shift `source ven/bin/activate` to the next line. Writing the two commands together might cause confusions.

**Comment by ighosh98** [comment]
Fix the error and send a PR @UnlaxedNeurotic. Let Abhishek review it

**Comment by ighosh98** [comment]
@UnlaxedNeurotic is this done? If yes, send your PR
