### ISSUE TITLE
Port data from the current website to the new website

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#43]
Data needs to be transferred from the current WordPress website to the new Freelunch Django based website. The assignee will have access to the backend of the website once they have figured out a solution. Feel free to discuss via comments on the issue

**Comment by Ak-shay** [comment]
which database was used by the previous website?

**Comment by ighosh98** [comment]
WordPress uses MySQL as its database management system. We also need to decide on the database we want to use for this website. I was thinking Postgres should do the job. Thoughts @abhishekspeer @Ak-shay ?

**Comment by ighosh98** [comment]
Data has been shared with members responsible for backend development(@UnlaxedNeurotic, @Ak-shay, @abhishekspeer and @ighosh98 ) in .sql format. Analyze the database provided before proceeding any further.

**Comment by ighosh98** [comment]
[Postgres setup tutorial](https://tecadmin.net/install-postgresql-server-on-ubuntu/)
