### ISSUE TITLE
Models to handle to diff kind of users, their permissions and basic info.

### ISSUE THREAD

**Issue by Ak-shay** [BITS-Periodical-Society/freelunch#45]
We have a page 'about'  in which we will show some basic info like name, email, bio ...etc
This page will have list of all users (developers, editors, chief-editor..etc).
We can have two types user which have any permissions and other with none. But their info will be their in db.
First we need to gather info about types of users and their permissions.
Then ideas to manage to them all.

**Comment by ighosh98** [comment]
Task 1: Gather all info from the site database. Discuss and finalize the Schema. 
@UnlaxedNeurotic @Ak-shay @abhishekspeer

**Comment by Ak-shay** [comment]
I am thinking to have 3 models:
Author
Editor
Developer
And Chief editor which will be a Editor, will be given permissions manually

**Comment by ighosh98** [comment]
That seems fine. Detail the model plans please

**Comment by Ak-shay** [comment]
In the Post model we will have created_by and edited_by
In the contributors page we will add all 3 models  detail.

**Comment by Ak-shay** [comment]
In PR #68, I have almost covered all schema. Here is a detail for the same:

1. **Post** Model
It have `auhtor` and `post_editor` for referencing `Writer` and `Editor` of post.
A `synopsis` to show under the title
A `post` will have  a section.
`content` is a Text field. We will use pagedown libraries. 
 
2. **Developer** Model
It will contain db for our team with their designation  and basic details like `name`, `pic`, `github_url`, `linkedin_url`, `email`, `bio`.
For now I have  added two `designation`. We can add more easily in future. But it will be a single choice.

3. **Editor** Model
same as `Developer` Model but  it dont have github and linkedin.
Also have `edited_posts` to refer posts edited by `editor`.

4. **Writer** Model
Same as `Edior` Model.
Only change is `posts` field which is used to refer `post` writen by `Writer`.

5. **Subscriber** Model
It will have `name` and `email` of our subscribers.

For more reference you can look `flapp/models.py`

**Comment by ighosh98** [comment]
Closing Issue.

**Comment by ighosh98** [comment]
Do all schema related discussion on #43 . This issue is sorted. Closing this. Apologies for the confusion. If something is left @Ak-shay you can reopen it
