### ISSUE TITLE
Add a info template which have about the author, also complete the author template 

### ISSUE THREAD

**Issue by Ak-shay** [BITS-Periodical-Society/freelunch#47]
Like in the previous site [Author](http://www.freelunch.co.in/authors/) template should have list with links and designation.
After clicking the name it should redirect us to author info [like this](http://www.freelunch.co.in/?author_name=aaditaya-raj-roshan). So add an info template with all required fields.

**Comment by ighosh98** [comment]
@HimanshuAgarwal022 please add the templates. Specifics can be clarified on the group, but I think the description made is clear enough
Deadline: 24th June 2019

**Comment by ighosh98** [comment]
I will handle this one with @JessePinkman7 .
Deadline: 24th June 2019

**Comment by Ak-shay** [comment]
Also add the dropdown for author info...As discussed @ighosh98 
After frontend will be done, I will do backend for the same

**Comment by ighosh98** [comment]
Template ideas:
1. https://liveramp.com/about-us/#leadership
2. https://jsfiddle.net/StartBootstrap/2Lkm6e1j/?utm_source=website&utm_medium=embed&utm_campaign=2Lkm6e1j

**Comment by Ak-shay** [comment]
2nd seems great....
We should have something like that only...

**Comment by ighosh98** [comment]
Added.
