### ISSUE TITLE
Add Documentation for the code base

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#48]
Everyone contributing code to the project must add documentation while making their PRs. How?
We would be using sphinx. Relevant docs for you guys to go through and understand:
- [The Official Django documentation](https://docs.djangoproject.com/en/dev/internals/contributing/writing-documentation/#getting-started-with-sphinx)
- [Official Sphinx Documentation](http://www.sphinx-doc.org/en/master/)
- [Tutorial on Documentation using Sphinx](https://realpython.com/kickstarting-a-django-open-source-project/#documentation)
- [Video Tutorials](https://www.youtube.com/playlist?list=PLcAljDQ0plzVF9nMghlVJ7Vwv6nQ4q5BH) **Note**: Some of it might be repetitive. Skim through whatever you feel is necessary.
- [Walkthrough on a sample project](http://www.marinamele.com/taskbuster-django-tutorial/documenting-project-github-readthedocs)
Here's a [sample project](https://github.com/agonzalezro/django-documentation-example) on Github for your reference

**Comment by ighosh98** [comment]
Before going through the official Sphinx documentation, go through the tutorial or/and videos. Definitely go through the sample projects.

**Comment by Ak-shay** [comment]
@UnlaxedNeurotic 
Whats the status?

**Comment by ighosh98** [comment]
I am assuming everyone has gone through the tutorials. I'll add details to Contributing.MD for the same. Closing issue.
