### ISSUE TITLE
changing post content field to something easy to beautify its content

### ISSUE THREAD

**Issue by Ak-shay** [BITS-Periodical-Society/freelunch#56]
I have come across an  applicaion [tinyMCE](https://www.tiny.cloud/) for the same.
[Here](https://fosstack.com/how-to-set-up-tinymce-in-django-app/) is the tutorial for same.
More ideas are welcome.

**Comment by ighosh98** [comment]
Please add more specific details on the issue at @Ak-shay .

**Comment by ighosh98** [comment]
Deadline:30th June

**Comment by ighosh98** [comment]
Some more editors I found:
1.[Medium Rich Text Editor Clone](https://github.com/yabwe/medium-editor)
2. [Quill](https://quilljs.com/)
3. [Medium Clone 2](https://github.com/orthes/medium-editor-insert-plugin)
4. [Textbox](https://textbox.io/wysiwyg-html-editor/)
5.[CKEditor](https://ckeditor.com/)

However, I feel we can continue with TinyMCE. @Ak-shay @abhishekspeer can you suggest any other alternatives? Probably a long term goal could be to build a custom wysiwyg rich text editor?

**Comment by ighosh98** [comment]
#68 introduced TinyMCE for hosting the website. Keep looking for alternative editors

**Comment by Ak-shay** [comment]
Pagedown libraries are being used now.

**Comment by ighosh98** [comment]
Closing issue. Solved by #77
