### ISSUE TITLE
Strategy Discussion for Suggested Articles Feature

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#6]
Develop an article recommender system which :
- [x] Recommends similar articles to the user. 
- [x] In the infinite scroll ensures that similar articles are shown one after the other.

**Comment by ighosh98** [comment]
@Ak-shay spend some time searching for a possible solution to this problem. This should be a challenging and interesting issue to work on as it combines the concepts of recommender systems with web development. The core idea is to deploy a recommender system(ML algorithm) on the database. We can start with a tag-based recommender system. Think over it when you get time.

**Comment by ighosh98** [comment]
Resources Worth Looking at:
- https://github.com/fcurella/django-recommends
- https://towardsdatascience.com/there-are-two-very-different-ways-to-deploy-ml-models-heres-both-ce2e97c7b9b1

**Comment by ighosh98** [comment]
@Ak-shay @UnlaxedNeurotic @abhishekspeer 
Let me know if we should implement an ML model in our case. (If you would like to)
 Your machine learning stuff can go to the VIEWS or the MODELS depending on what you want to do.
A useful thing worth noting:  If you are using SKLEARN, it is a module and can be used just like any regular module like: requests, Pandas, numpy, etc.

Reference reading material: 
We can use the Django REST API for our work. “Train/predict simple machine learning models with Django REST.” by Mahdi Ghelichi https://link.medium.com/r3cfG1PHKX you can start with this and start building for your usecase
I have reference books which talk about building a recommender system in Django(for slightly different purposes).

**Comment by ighosh98** [comment]
We'll follow the tag based strategy for this. ML would make the website very slow

**Comment by Ak-shay** [comment]
Tasks:
- [ ] Add Tag model
- [ ] Make a function that returns recommended articles by using tags then categories then all...
- [ ] All should be sorted by time and date
- [ ] Add recommendations in templates.

**Comment by ighosh98** [comment]
I'll create a new for the same. Closing this one.
