### ISSUE TITLE
Articles are not loading properly.

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#60]
- [x] Articles are not loading properly. Summary and articles are getting mixed. The home page should only have the summary/synopsis of the article. The new page it hyperlinks to does not show the entire article.
- [x] Articles are not loading as of now when you go to the new page
- [x] Add a script to automatically separate the synopsis and main article.
- [x] Add a button that reads **Read More**. It should hyperlink to the article.
- [x] Ensure that hovering over the article does not change its color due to the hyperlink added.

**Comment by ighosh98** [comment]
@HimanshuAgarwal022 add a read more button for every article in the template and help @Ak-shay  wherever he needs help. It's your code. You know it the best

**Comment by ighosh98** [comment]
Only Read More button and the hyperlink issue are left @HimanshuAgarwal022 . Finish this so that we can close this issue

**Comment by ighosh98** [comment]
I have fixed the hyperlink issue in #114.

**Comment by Ak-shay** [comment]
Is this solved ?
@HimanshuAgarwal022 have u added `read more` in your new templates?

**Comment by HimanshuAgarwal022** [comment]
yes I have added the read more button and some major frontend enhancements.
will commit soon.

**Comment by ighosh98** [comment]
#118 solved this
