### ISSUE TITLE
Add Documentation for closed PRs

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#62]
@UnlaxedNeurotic  

- [ ] Add sphinx based detailed documentation for the following PRs. Refer to #48 for tutorials
   -  #42 
   -  #44 
- [ ]  Go through the list of PRs and create a list of major PRs which are to be documented and add a comment. There should be no redundancy.

From this list, others(@HimanshuAgarwal022, @Ak-shay @JessePinkman7 ) would pick two PRs that you have worked on or would like to document.

**Comment by Ak-shay** [comment]
@UnlaxedNeurotic 
You should start this.
