### ISSUE TITLE
Add Subscribe Feature

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#64]
Subtasks
- [x] Add a button which allows users to subscribe using E-Mail IDs and their name.
- [x] Also create a database for storing information of the subscribers.
- [x]  Add necessary frontend

**Comment by Ak-shay** [comment]
I have created model for same... 
Just need to do some frontend to show form.

**Comment by ighosh98** [comment]
@JessePinkman7 you're up. Create the form.

**Comment by ighosh98** [comment]
@Ak-shay finish this please.

**Comment by Ak-shay** [comment]
Where should we add subscribe form?

**Comment by ighosh98** [comment]
We could do one of the two:
1. Don't add a form. Just a bar where users can enter their details.
2.  Or we could also add it to the right of the post_list and post_detail pages(like in the previous site). Similar implementation to Comments forms. Just position things properly. @UnlaxedNeurotic can take this up. You can post the required fields on the thread.
@Ak-shay which one is better in your opinion?

**Comment by unlaxedneurotic** [comment]
Fixed in #154
