### ISSUE TITLE
Automate Fake Data Creation

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#66]
Search for automated methods to create fake data for testing purposes. Suggestions are welcome. Related to #43

**Comment by ighosh98** [comment]
Frameworks we can use:
- [Django-Autofixture](https://pypi.org/project/django-autofixture/)
- [Django-Dilla](https://github.com/aerosol/django-dilla)
- [Django Mockups](https://github.com/sorl/django-mockups) : There hasn't been much development activity on this project.
Which one should we use @UnlaxedNeurotic @Ak-shay ?

**Comment by unlaxedneurotic** [comment]
Cannot use django mockups. Does not work with python3.x. Many syntax and import errors

**Comment by unlaxedneurotic** [comment]
Actually, none of these are viable. Django-Dilla was last updated around 8 years ago. And Autofixture only supports django 1.4-1.9. I was looking at other options but not many are available. [Faker](https://faker.readthedocs.io/en/stable/) [(check repo)](https://github.com/joke2k/faker) is recently updated but it is does not seem to be built for django. Just a general python fake data creator. But we may be able to implement it. @ighosh98

**Comment by ighosh98** [comment]
Go through the documentation once. Work on implementing that in a separate repo. @UnlaxedNeurotic

**Comment by ighosh98** [comment]
Field formats we would need:
1. Fake name 
2. Fake MAIL ID
3. Fake text
4. Fake dates
So, faker seems to be alright in general, but data is generated in XML format. We would need to convert the data into a SQL type format.

**Comment by ighosh98** [comment]
@UnlaxedNeurotic can implement this one.

**Comment by unlaxedneurotic** [comment]
Fixed in #144
