### ISSUE TITLE
Modify CSS template for columns

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#69]
Modify Columns in such a way that we can automate the process of postioning the image.

- [x] We are currently using column1, column2, and column3 as classes. This is making it difficult tow write a for loop. (You can either write the for loop or come up with a modification of the CSS which allows us to write the for loop easily)
- [x] Fix the card template.

You can drop me a message or comment below for further clarifications.

**Comment by ighosh98** [comment]
**Note** : This is a very urgent issue. Needs to be sorted out first and foremost.

**Comment by ighosh98** [comment]
@Ak-shay is the solution we discussed working? If yes, commit the code to #68 .

**Comment by Ak-shay** [comment]
That column issue is solved but now I need a solution to div row class after 3 loops..

**Comment by ighosh98** [comment]
Commit the code. We can have a look at it and try to figure out a solution

**Comment by ighosh98** [comment]
@Ak-shay will commit the code and add a comment here with details on the code and database structure. 
@HimanshuAgarwal022 @JessePinkman7 
1. Work on the branch templates-backend.
2.  So as of now we have a blog.css(flapp/static/css/blog.css). Look for the classes column1,column2 and column3. They govern the position of the images. 
Task: We need to automate the transfer of data from sqllite dbs to the webpage. @Ak-shay has managed to figure out how to automate adding to the columns in a cyclic manner. However, we need to change the row(see row class in blog.css) after the third column is filled for obvious reasone. Your task is to ensure this functionality is implemented.
In the end you must have a function which adds images to the three columns and then moves to the next row. 
Ideas: You could either modfiy the CSS or write a JS to track when one cycle is finished and move to the next row. 
**Skills Required** : JS/jQuery

**Comment by ighosh98** [comment]
@HimanshuAgarwal022  comments have been added to the issue. Look at #68 . The last commit.

**Comment by ighosh98** [comment]
Merging #68

**Comment by ighosh98** [comment]
Row issues still need to be sorted. @HimanshuAgarwal022 @JessePinkman7 
Make a PR once that is done. I would then close this issue

**Comment by ighosh98** [comment]
Card template is fixed. Refer to #77 .

**Comment by ighosh98** [comment]
Fixed by @HimanshuAgarwal022 . Good job! Refer to PR #77
