### ISSUE TITLE
Modify Template for Writers and Developers

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#73]
Modify the code for profile_page.html such that the following features are found:
- [x] For writers we have a field where the articles are shown. Hence add the article view to this issue.
- [x] Social media(LinkedIn and Github) fields must be shown on the personal website. If the field is NULL make it invisible, else add a hyperlink to the user's profile. As of now, just add those two symbols with hyperlink.

Sections of the article:
- [x] Photo
- [x] Bio
- [x] Connect with Me[Social profile]
- [x] Links to all the articles written by the user

**Comment by HimanshuAgarwal022** [comment]
so a for loop to filter the articles by the writer rest the template remains the same?

**Comment by ighosh98** [comment]
@HimanshuAgarwal022 Um yeah. That should do the trick. 
You will need a condition for deciding if the profile is of a writer or developer. Discuss this part once with @Ak-shay. I feel this can be made into a single template with an if condition.

**Comment by ighosh98** [comment]
Backend is done. @Ak-shay is working on frontend.

**Comment by ighosh98** [comment]
@Ak-shay Keep the footer as it is. That would link to the main website. Additionally, add a section for the social of a user. Make the template of a user like his personal webpage with a short bio and Connect with Me section for social media links

**Comment by ighosh98** [comment]
Template idea:
https://www.wix.com/website-template/view/html/2206?siteId=86816562-8681-4b95-a9ea-6eb4178a1654&metaSiteId=a5028e92-a237-4abd-bde5-9c1e0f0839b0&originUrl=https%3A%2F%2Fwww.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Fblogs-and-forums

**Comment by ighosh98** [comment]
@Ak-shay make it a variation of that template.
