### ISSUE TITLE
Fix the Nav Bar

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#78]
- [x] Nav Bar does not slide properly when moving from top to below on the web page. Must be fixed and made consistent. It disappears while you are making the slide. Fix this.
- [x] There is a gap created between top of the window and top of the nav bar while moving up. This must be fixed.

**Comment by HimanshuAgarwal022** [comment]
I can't find any issue please clarify...

**Comment by ighosh98** [comment]
@HimanshuAgarwal022 This was discussed on the group.  The tasks have been detailed again as well.

**Comment by ighosh98** [comment]
Closing. Solved by #90

**Comment by ighosh98** [comment]
We still have some issues in th Nav Bar. @UnlaxedNeurotic please clarify the issues.
