### ISSUE TITLE
Do not allow the writer or editor to add an article in their models.

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#84]
Refer to point 1 of #77 
The issue can be discussed further over a phone call.

**Comment by Ak-shay** [comment]
Writer and Editor will not have admin credential ...
Only Chief editor will have it.
Writer and Editor will be populated by Chief only.

**Comment by Ak-shay** [comment]
For now you a credential of a superuser, which every single permission.
I am thinking to make Chief Editor with custom permissions.
And we can also give editor and writer a staff user credential with our custom permmission.

**Comment by Ak-shay** [comment]
I will add certain methods to automate the process of adding articles..

**Comment by ighosh98** [comment]
Related to #87.

**Comment by ighosh98** [comment]
Is this done? @Ak-shay

**Comment by ighosh98** [comment]
Closing Issue. Need to add necessary documentation for the same.
