### ISSUE TITLE
Adding font style options for the Article

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#86]
Refer to issue #77.
- [ ] Give the editor a few more options for the font.

**Note**: Not necessary to be implemented. The current font looks alright. But it would be nice if we could test a couple more fonts and decide which works best]

**Comment by Ak-shay** [comment]
We have '#' for that. It works like html heading 
# #for h1
## ##for h2
so on till h6

**Comment by ighosh98** [comment]
I mean font style @Ak-shay . Sorry for the confusion

**Comment by ighosh98** [comment]
Look for plugins or frameworks to solve this issue.  Issue is related to #3.

**Comment by ighosh98** [comment]
Fixed a font style in #114 .
