### ISSUE TITLE
Change footer for profile page template

### ISSUE THREAD

**Issue by Ak-shay** [BITS-Periodical-Society/freelunch#91]
Our footer is in base.html now, we extending it to every template which creates a bug in profile page template..
As we need that links to redirect to respective user..
footer on other page should redirect to freelunch profiles on social media.
Also we need linkedIn, Github logos.
Also a mail logo to add email

**Comment by ighosh98** [comment]
@Ak-shay Keep that footer. That would link to the main website. Add a section in #73 for the social of a user. Make the template of a user like his personal webpage with a short bio and **Connect with Me** section for social media links. Closing this issue. Work on #73.
