### ISSUE TITLE
Make CSS Responsive

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#92]
- [x] Fix size of box
- [x] Fix the position of Find out More
- [x] Add Hovering over image[Hovering overlay]

**Comment by ighosh98** [comment]
Don't use card-deck.

**Comment by ighosh98** [comment]
@HimanshuAgarwal022 please fix the position of the Find Out More button by fixing the CSS. I am getting inconsistent observations on my laptop. Use the **branch patch-f** to work. Everything else works perfectly.
Current situation: **Find out More** is positioned inappropriately in an asymmetric manner. Make the positioning symmetric for a given row by modifying the CSS appropriately.

**Comment by Ak-shay** [comment]
Its done in comment branch

**Comment by ighosh98** [comment]
Solved using #96.
