### ISSUE TITLE
Modify the comments section template

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#99]
- [x] Don't hyperlink to a new page while adding a comment. Load the comments section on the same page

**Comment by ighosh98** [comment]
Still not solved. @UnlaxedNeurotic keep working on it.

**Comment by HimanshuAgarwal022** [comment]
maybe we can implement facebook comment plugin for Django
it's simple and efficient.
https://developers.facebook.com/docs/plugins

**Comment by ighosh98** [comment]
@HimanshuAgarwal022 Similar to the fb comment system or add the plugin FB comment plugin to our web app? There is a solution to this problem available online(As discussed with @Ak-shay ). Let @UnlaxedNeurotic search for it.

**Comment by HimanshuAgarwal022** [comment]
no add the same FB plugin as it is. also maybe like and share on fb etc.
@UnlaxedNeurotic @ighosh98
